### ISSUE TITLE
triangle

### ISSUE THREAD

**Issue by lisowska** [wookoinc/react-native-popover-tooltip#1]
hi,
It is possible to change the position of triangle. I want to add marginLeft, but now it is not possible.

**Comment by luqiuyuan** [comment]
Hello, yes currently the position of the triangle cannot be changed, it is in the middle of the buttonComponent by default. What type of margin do you need, the margin relative to the buttonComponent or the margin relative to the popover tooltip?

**Comment by lisowska** [comment]
Hello @luqiuyuan I think margin relative to the popover tooltip.Now triangle looks like in image tooltip1a [,](url) 
![tooltip1a](https://user-images.githubusercontent.com/13997469/28263127-94e3d102-6add-11e7-97a3-a940cfe8c9e1.png) but I want to change marginLeft to 3 to see triangle looks like in image tooltip1b 
![tooltip1b](https://user-images.githubusercontent.com/13997469/28263143-a2f704e4-6add-11e7-87bf-18f18ee2b297.png)

**Comment by luqiuyuan** [comment]
Hello @lisowska we have added this feature on our todo list. However, we are quite busy recently and will do it after we got time. Will let you know when it is added. If you want to submit a pull request, it is also welcome.

**Comment by lisowska** [comment]
hello @luqiuyuan thank you for your message

**Comment by Daadler6** [comment]
@luqiuyuan went ahead and opened a PR that will fix this issue. While it is not needed for our production app I figured it would be a nice feature. https://github.com/wookoinc/react-native-popover-tooltip/pull/12

**Comment by luqiuyuan** [comment]
Thanks to @Daadler6 , the component now has this feature, you can just triangleOffset to set the position of the triangle! @lisowska

**Comment by Daadler6** [comment]
@lisowska this feature is now live. If you want to validate and close this issue
