### ISSUE TITLE
ToolTip Appears Off Screen when near Bottom and setBelow enabled

### ISSUE THREAD

**Issue by Daadler6** [wookoinc/react-native-popover-tooltip#10]
As per our earlier discussion we have a fix for the issue you mentioned where the Tooltip will go off the screen when near the bottom of the screen. Simple fix was to simple enforce it to flip to appear above. Please let me know if you have any questions or concerns with the PR and we can update.

https://github.com/wookoinc/react-native-popover-tooltip/pull/9

**Comment by luqiuyuan** [comment]
@Daadler6 I have merged this PR, it works like a charm!
