### ISSUE TITLE
Unstable for android, move modal outside so that it can be used like a Provider or add a modal render block.

### ISSUE THREAD

**Issue by j-mendez** [wookoinc/react-native-popover-tooltip#15]

**Comment by lorderikir** [comment]
WOWOWOWOWOWOWWOWOWOWO

**Comment by ericjiang97** [comment]
WOW SUCH DESCRIPTION, MUCH WORDS.

**Comment by j-mendez** [comment]
Not sure what happened to my description. I think when I was using this package prior to the position of the tooltip was incorrect depending on the distance away from the edges of the screen. I will retest soon. Sorry about that waste of time.
