### ISSUE TITLE
PropTypes is deprecated in React 15.5

### ISSUE THREAD

**Issue by FedeG** [wookoinc/react-native-popover-tooltip#5]
I updated react-native-tooltip-menu compatibility for react 16 in this merge: https://github.com/alimek/react-native-tooltip-menu/pull/7

**Comment by FedeG** [comment]
I'm develop to update this repository in this fork: https://github.com/Devecoop/react-native-popover-tooltip

**Comment by FedeG** [comment]
This issue are fixed in this pull request: https://github.com/wookoinc/react-native-popover-tooltip/pull/6

**Comment by luqiuyuan** [comment]
FedeG, sorry to the late reply. Thanks for sending the PR. However, I merged your change manually, since the PR contains some other changes.

**Comment by beetlebum** [comment]
@luqiuyuan seems like only `index.js` was modified, but `popovertooltipitem.js` also contains references to `React.PropTypes` and won't work in React 16.

**Comment by Daadler6** [comment]
I am working on a PR for this issue. Will have one shortly.

**Comment by luqiuyuan** [comment]
@beetlebum Yes, it was my mistake, I forgot to change popovertooltipitem.js. However, I have merged the PR from @Daadler6 , it should be OK now.

**Comment by Daadler6** [comment]
@FedeG can we get this issue closed?
