### ISSUE TITLE
Unable to set tooltip position below target.

### ISSUE THREAD

**Issue by Daadler6** [wookoinc/react-native-popover-tooltip#8]
WookInc. First off love this package thanks for creating it! The current implementation fits 95% of our AC but we had to roll a custom version of it because we need to default the tooltip below the target no matter the position. I've created a PR that reflects the changes we made in our custom version. It adds a setBelow property to override the default to appear above the target. Please feel free to add any feedback on the PR or let me know if you have any questions.

https://github.com/wookoinc/react-native-popover-tooltip/pull/7

**Comment by luqiuyuan** [comment]
Hi Daadler6, thanks for submitting this pull request. We appreciate your contribution a lot. I have tested the commits, it works like a charm. I have merged the PR.

And I found there are two issues when the tooltip pops up from below (not introduced by your codes).
First one is that the start point of the animation is not from the corner of the triangle.
Second one is that when the button is near the bottom of the screen, the tooltip might go outside of the screen.

The two issues are on my schedule, however I am working in another project this month in a rush. I will find time to solve them next month. But if you have solved the two issues, PRs are welcome.

**Comment by Daadler6** [comment]
Luqiuyuan. Thanks for the merge it will really help us out in our production application. As for those issues I can have myself and my team look into them this week. We love the package so anything do make it better. I'll see if we can open some PRs this week to resolve those issues as I am sure they will effect our app as well.

**Comment by Daadler6** [comment]
Closing this issue since this thread does not apply to the original change request
